name: Build

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Fetch Ruby dependencies
        run: make target/vendor

      - name: Fetch eForms SDK
        run: make target/eforms-sdk

      - name: Status
        run: make status

      - name: Build folder
        run: make build