name: Build

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare version labels
        uses: k15g/action-version-labels@v1
        with:
          prefix: project

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Fetch Ruby dependencies
        run: make .bundle/vendor

      - name: Fetch eForms SDK
        run: make target/eforms-sdk

      - name: Status
        run: make status

      - name: Build folder
        run: make build

      - name: Package
        run: make package

      - name: Upload bundle (artifact)
        uses: actions/upload-artifact@v2
        with:
          path: target/*.tar.gz
          name: eforms-sdk-nor-resources-${{ env.PROJECT_VERSION }}
          retention-days: 3

      - name: Upload bundle (artifact)
        uses: actions/upload-artifact@v2
        with:
          path: target/*.zip
          name: eforms-sdk-nor-resources-${{ env.PROJECT_VERSION }}
          retention-days: 3