name: Build

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  versions:
    name: Extract versions
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ env.MATRIX }}
      version: ${{ env.PROJECT_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare version labels
        uses: k15g/action-version-labels@v1
        with:
          prefix: project

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Fetch Ruby dependencies
        run: make .bundle/vendor

      - name: Fetch versions
        run: |
          make versions
          make versions >> $GITHUB_ENV


  build_bundle:
    name: Build SDK bundle
    runs-on: ubuntu-latest
    needs: versions

    strategy:
      matrix: 
        include: ${{fromJSON(needs.versions.outputs.matrix)}}

    env:
      EFORMS_MINOR: ${{ matrix.EFORMS_MINOR }}
      EFORMS_PATCH: ${{ matrix.EFORMS_PATCH }}
      PROJECT_VERSION: ${{needs.versions.outputs.version}}
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Fetch Ruby dependencies
        run: make .bundle/vendor

      - name: Fetch eForms SDK
        run: make target/eforms-sdk

      - name: Status
        run: make status

      - name: Build folder
        run: make build

      - name: Build validator
        run: make validator

      - name: Package
        run: make package

      - name: Upload bundle (artifact)
        uses: actions/upload-artifact@v3
        with:
          path: target/*.tar.gz
          name: eforms-sdk-nor-resources-${{ matrix.EFORMS_MINOR }}-${{ env.PROJECT_VERSION }}
          retention-days: 3

      - name: Upload bundle (artifact)
        uses: actions/upload-artifact@v3
        with:
          path: target/*.zip
          name: eforms-sdk-nor-resources-${{ matrix.EFORMS_MINOR }}-${{ env.PROJECT_VERSION }}
          retention-days: 3

      - name: Upload bundle (artifact)
        uses: actions/upload-artifact@v3
        with:
          path: target/*.asice
          name: eforms-sdk-nor-resources-${{ matrix.EFORMS_MINOR }}-${{ env.PROJECT_VERSION }}
          retention-days: 3

      - name: Upload publishing.tar.gz
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/eforms-sdk-nor-${{ env.PROJECT_VERSION }}.tar.gz
          name: eforms-sdk-${{ matrix.EFORMS_MINOR }}-nor-${{ env.PROJECT_VERSION }}.tar.gz
          label: eForms SDK NOR ${{ env.PROJECT_VERSION }} for ${{ matrix.EFORMS_MINOR }} (tar.gz)

      - name: Upload publishing.zip
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/eforms-sdk-nor-${{ env.PROJECT_VERSION }}.zip
          name: eforms-sdk-${{ matrix.EFORMS_MINOR }}-nor-${{ env.PROJECT_VERSION }}.zip
          label: eForms SDK NOR ${{ env.PROJECT_VERSION }} for ${{ matrix.EFORMS_MINOR }} (zip)

      - name: Upload validation
        uses: k15g/action-github-asset-upload@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/dev.anskaffelser.eforms.sdk-nor.asice
          name: dev.anskaffelser.eforms.sdk-${{ matrix.EFORMS_MINOR }}-nor-${{ env.PROJECT_VERSION }}.asice.zip
          label: Validaton for eForms SDK ${{ matrix.EFORMS_MINOR }} NOR